version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: thewavebeta
    restart: always
    ports:
    - 3306:3306
    expose: [3306]
    volumes:
    - dbdata:/var/lib/mysql

volumes:
  dbdata: